<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfL8E8B\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfL8E8B/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQfL8E8B.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQfL8E8B\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQfL8E8B\appAppKernelProdContainer([
    'container.build_hash' => 'QfL8E8B',
    'container.build_id' => '5fef2987',
    'container.build_time' => 1760451964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfL8E8B');
