<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxDesign\Controller\Admin\AdminPsxDesignColorsController' shared autowired service.

$this->services['PrestaShop\\Module\\PsxDesign\\Controller\\Admin\\AdminPsxDesignColorsController'] = $instance = new \PrestaShop\Module\PsxDesign\Controller\Admin\AdminPsxDesignColorsController();

$instance->setContainer($this);

return $instance;
