<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\PsxDesign\Controller\Admin\AdminPsxDesignThemeGeneralController' shared autowired service.

$this->services['PrestaShop\\Module\\PsxDesign\\Controller\\Admin\\AdminPsxDesignThemeGeneralController'] = $instance = new \PrestaShop\Module\PsxDesign\Controller\Admin\AdminPsxDesignThemeGeneralController(($this->services['prestashop.core.addon.theme.repository'] ?? $this->load('getPrestashop_Core_Addon_Theme_RepositoryService.php')));

$instance->setContainer($this);

return $instance;
