<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'psxdesign.http_client' shared service.

return $this->services['psxdesign.http_client'] = new \PrestaShop\Module\PsxDesign\Http\HttpClient();
