<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'prestashop.module.psxdesign.token_encoder' shared service.

return $this->services['prestashop.module.psxdesign.token_encoder'] = new \Lcobucci\JWT\Encoding\JoseEncoder();
