<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\Module\DistributionApiClient\Controller\Admin\TopContributorsController' shared autowired service.

$this->services['PrestaShop\\Module\\DistributionApiClient\\Controller\\Admin\\TopContributorsController'] = $instance = new \PrestaShop\Module\DistributionApiClient\Controller\Admin\TopContributorsController();

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
    'form.factory' => ['services', 'form.factory', 'getForm_FactoryService.php', true],
    'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
    'router' => ['services', 'prestashop.router', 'getPrestashop_RouterService.php', true],
    'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'security.csrf.token_manager' => ['services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
    'security.token_storage' => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
    'session' => ['services', 'session', 'getSessionService', false],
    'twig' => ['services', 'twig', 'getTwigService.php', true],
], [
    'doctrine' => '?',
    'form.factory' => '?',
    'http_kernel' => '?',
    'parameter_bag' => '?',
    'request_stack' => '?',
    'router' => '?',
    'security.authorization_checker' => '?',
    'security.csrf.token_manager' => '?',
    'security.token_storage' => '?',
    'serializer' => '?',
    'session' => '?',
    'twig' => '?',
]))->withContext('PrestaShop\\Module\\DistributionApiClient\\Controller\\Admin\\TopContributorsController', $this));

return $instance;
